#!/usr/bin/env Rscript

# ==============================================================================
# Description:  Produces publication-ready figures summarizing associations
#               between CD43/SPN expression and CIBERSORTx LM22 immune-cell
#               fractions across ten TCGA cancer cohorts. The script visualizes
#               both complementary analyses generated by Script 04: continuous
#               Spearman correlations across all samples and CD43-high versus
#               CD43-low rank-biserial effect sizes. It then summarizes the
#               complete 22-cell LM22 composition of the CD43-low and CD43-high
#               groups within every cancer. Complete composition is displayed
#               as a separate butterfly profile for each cancer: CD43-low
#               fractions extend left and CD43-high fractions extend right.
#
#               The plotting style follows the project's established figures:
#               classic white background, thin dark axes, no panel grid,
#               black-outlined filled points, bold unboxed facet labels,
#               compact grey axis text, and restrained rose accents. Signed
#               effects use muted blue for negative associations, white for
#               zero, and rose for positive associations. Black asterisks mark
#               associations with within-cancer BH-FDR <= 0.05.
#
# Inputs:       1. results/04/04_all_cancers_SPN_correlations.csv
#                  Continuous SPN-expression/LM22 Spearman results from Script 04.
#               2. results/04/04_all_cancers_CD43_high_vs_low.csv
#                  Quartile-group Wilcoxon and rank-biserial results from Script 04.
#               3. data/analysis_ready/all_cancers_analysis_ready.tsv.gz
#                  Sample-level CD43 groups and CIBERSORTx LM22 fractions from
#                  Script 03.
#
# Outputs:      results/05/
#               1. figures/05A_cross_cancer_spearman_heatmap.png
#               2. figures/05B_cross_cancer_rank_biserial_heatmap.png
#               3. figures/per_cancer/05C_<CANCER>_CD43_butterfly_profile.png
#                  One figure for each of the ten cancer cohorts.
#               4. 05_composition_summary.csv
#               5. 05_figure_manifest.csv
#               6. 05_sessionInfo.txt
#
# Analysis set: Primary results including all successfully deconvolved samples.
#
# Interpretation: Positive values indicate larger relative fractions with
#               higher SPN expression or in CD43-high tumors. Negative values
#               indicate the opposite. LM22 outputs are relative/compositional
#               fractions and these associations do not establish causality.
#               LAML and THYM are marked as special biological contexts because
#               malignant hematopoietic cells or developing thymocytes can
#               resemble LM22 reference populations.
#
# Usage:        Rscript src/05_plot_cd43_immune_associations.R
#
# Dependencies: R packages data.table, ggplot2, scales
# ==============================================================================

options(stringsAsFactors = FALSE)

required_packages <- c("data.table", "ggplot2", "scales")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0L) {
  stop(
    "Install the missing package(s): ",
    paste(missing_packages, collapse = ", ")
  )
}

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(scales)
})

# ==============================================================================
# File locations and plotting constants
# ==============================================================================

script04_results_dir <- file.path(getwd(), "results", "04")
results_dir <- file.path(getwd(), "results", "05")
analysis_file <- file.path(
  getwd(), "data", "analysis_ready", "all_cancers_analysis_ready.tsv.gz"
)
continuous_file <- file.path(
  script04_results_dir, "04_all_cancers_SPN_correlations.csv"
)
categorical_file <- file.path(
  script04_results_dir, "04_all_cancers_CD43_high_vs_low.csv"
)
figure_dir <- file.path(
  results_dir, "figures"
)

invisible(lapply(
  c(results_dir, figure_dir),
  dir.create,
  recursive = TRUE,
  showWarnings = FALSE
))

required_files <- c(continuous_file, categorical_file, analysis_file)
missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0L) {
  stop(
    "The following required input file(s) do not exist: ",
    paste(missing_files, collapse = ", ")
  )
}

cancer_order <- c(
  "GBM", "PAAD", "STAD", "TGCT", "SKCM", "UVM",
  "LUAD", "LUSC", "LAML", "THYM"
)

# Keep all cancers for supplementary profiles. For a melanoma-only main
# figure, change this line to: butterfly_cancers <- "SKCM"
butterfly_cancers <- cancer_order

cancer_strip_labels <- c(
  GBM = "GBM\nOverexpressed",
  PAAD = "PAAD\nOverexpressed",
  STAD = "STAD\nOverexpressed",
  TGCT = "TGCT\nOverexpressed",
  SKCM = "SKCM\nOverexpressed",
  UVM = "UVM\nOverexpressed",
  LUAD = "LUAD\nUnderexpressed",
  LUSC = "LUSC\nUnderexpressed",
  LAML = "LAML\nOverexpressed*",
  THYM = "THYM\nOverexpressed*"
)

rose <- "#A83F55"
pale_rose <- "#E9B6BF"
muted_blue <- "#3D7EA6"
near_white <- "#F7F7F7"
dark_grey <- "grey25"
text_grey <- "grey30"

cd43_low_colour  <- "#62B6E7"
cd43_high_colour <- "#FC4E92"

cd43_low_border  <- "#347FA8"
cd43_high_border <- "#C8326D"

cd43_low_text  <- cd43_low_border
cd43_high_text <- cd43_high_border

significance_colour <- "grey20"
row_guide_colour <- "#EEF1F4"

lm22_palette <- c(
  "B cells naive" = "#9BD8D0",
  "B cells memory" = "#49AFA5",
  "Plasma cells" = "#176D68",
  "T cells CD8" = "#39B8E6",
  "T cells CD4 naive" = "#4A96D8",
  "T cells CD4 memory resting" = "#557BCB",
  "T cells CD4 memory activated" = "#655FBF",
  "T cells follicular helper" = "#7549B1",
  "T cells regulatory (Tregs)" = "#893C9F",
  "T cells gamma delta" = "#A13791",
  "NK cells resting" = "#E6BC45",
  "NK cells activated" = "#D99635",
  "Monocytes" = "#E88678",
  "Macrophages M0" = "#D76469",
  "Macrophages M1" = "#B94D5F",
  "Macrophages M2" = "#8F394E",
  "Dendritic cells resting" = "#A8C768",
  "Dendritic cells activated" = "#6FA55D",
  "Mast cells resting" = "#B58A68",
  "Mast cells activated" = "#805F52",
  "Eosinophils" = "#E678A9",
  "Neutrophils" = "#7D8790"
)

# ==============================================================================
# Reusable helpers
# ==============================================================================

project_theme <- function(base_size = 10) {
  theme_classic(base_size = base_size) +
    theme(
      plot.title = element_text(face = "bold", size = 13),
      plot.subtitle = element_text(size = 9, colour = text_grey),
      plot.caption = element_text(size = 7.5, colour = "grey40", hjust = 0),
      axis.title = element_text(size = 10),
      axis.text = element_text(size = 8, colour = text_grey),
      axis.ticks = element_blank(),
      axis.line = element_line(colour = dark_grey, linewidth = 0.4),
      strip.text = element_text(
        face = "bold", size = 8.5, margin = margin(t = 4, b = 4)
      ),
      strip.background = element_blank(),
      panel.grid = element_blank(),
      panel.spacing = unit(0.8, "lines"),
      legend.title = element_text(size = 9),
      legend.text = element_text(size = 8),
      legend.key.height = unit(0.38, "cm"),
      plot.margin = margin(8, 8, 8, 8)
    )
}

validate_columns <- function(dat, expected, object_name) {
  missing <- setdiff(expected, names(dat))
  if (length(missing) > 0L) {
    stop(
      object_name, " is missing required column(s): ",
      paste(missing, collapse = ", ")
    )
  }
}

fdr_symbol <- function(x) {
  fifelse(
    is.na(x), "",
    fifelse(
      x <= 0.001, "***",
      fifelse(x <= 0.01, "**", fifelse(x <= 0.05, "*", "ns"))
    )
  )
}

save_png <- function(plot, filename, width, height) {
  output_path <- file.path(figure_dir, filename)
  ggsave(
    filename = output_path,
    plot = plot,
    width = width,
    height = height,
    dpi = 600,
    bg = "white"
  )
  message("Saved: ", output_path)
  output_path
}

prepare_heatmap_data <- function(dat, value_column, fdr_column) {
  plot_data <- copy(dat)

  cell_order <- plot_data[, .(
    cross_cancer_median = median(get(value_column), na.rm = TRUE)
  ), by = cell_type][order(cross_cancer_median)]$cell_type

  plot_data[, cancer := factor(cancer, levels = cancer_order)]
  plot_data[, cell_type := factor(cell_type, levels = cell_order)]
  plot_data[, plot_value := get(value_column)]
  plot_data[, significant := get(fdr_column) <= 0.05]
  plot_data
}

make_heatmap <- function(
  plot_data,
  title,
  subtitle,
  legend_title,
  filename
) {
  effect_limit <- max(abs(plot_data$plot_value), na.rm = TRUE)

  p <- ggplot(
    plot_data,
    aes(x = cancer, y = cell_type, fill = plot_value)
  ) +
    geom_tile(colour = "white", linewidth = 0.45) +
    geom_point(
      data = plot_data[significant == TRUE],
      shape = 8,
      size = 1.45,
      stroke = 0.25,
      colour = "black"
    ) +
    scale_fill_gradient2(
      low = muted_blue,
      mid = near_white,
      high = rose,
      midpoint = 0,
      limits = c(-effect_limit, effect_limit),
      name = legend_title
    ) +
    labs(
      title = title,
      subtitle = subtitle,
      x = NULL,
      y = NULL,
      caption = paste0(
        "Black asterisks indicate within-cancer BH-FDR <= 0.05. ",
        "GBM through UVM are CD43-overexpressed solid tumors; LUAD and ",
        "LUSC are CD43-underexpressed solid tumors. LAML and THYM require ",
        "special biological interpretation."
      )
    ) +
    project_theme() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
      axis.text.y = element_text(size = 7.5),
      axis.line = element_blank(),
      legend.position = "right"
    )

  save_png(p, filename, width = 10.5, height = 10.5)
}

# ==============================================================================
# Read and validate results
# ==============================================================================

continuous <- fread(continuous_file, check.names = FALSE)
categorical <- fread(categorical_file, check.names = FALSE)
sample_data <- fread(analysis_file, check.names = FALSE)

validate_columns(
  continuous,
  c(
    "cancer", "analysis_set", "cell_type", "spearman_rho",
    "spearman_FDR"
  ),
  "Continuous association results"
)

validate_columns(
  categorical,
  c(
    "cancer", "analysis_set", "cell_type", "rank_biserial",
    "wilcoxon_FDR"
  ),
  "High-versus-low association results"
)

validate_columns(
  sample_data,
  c("cancer", "sample_id", "CD43_group", names(lm22_palette)),
  "Analysis-ready sample table"
)

continuous <- continuous[analysis_set == "primary_all_samples"]
categorical <- categorical[analysis_set == "primary_all_samples"]

if (nrow(continuous) == 0L || nrow(categorical) == 0L) {
  stop("No primary_all_samples results were found. Run Script 04 first.")
}

if (!setequal(unique(continuous$cancer), cancer_order)) {
  stop("Continuous results do not contain exactly the ten expected cancers.")
}

if (!setequal(unique(categorical$cancer), cancer_order)) {
  stop("Categorical results do not contain exactly the ten expected cancers.")
}

manifest <- data.table(
  figure = character(),
  description = character(),
  file = character()
)

# ==============================================================================
# Figure 05A: continuous Spearman correlation heatmap
# ==============================================================================

rho_plot_data <- prepare_heatmap_data(
  continuous,
  value_column = "spearman_rho",
  fdr_column = "spearman_FDR"
)

rho_path <- make_heatmap(
  rho_plot_data,
  title = "CD43 expression is associated with distinct immune-cell profiles",
  subtitle = paste0(
    "Spearman correlations between log2(SPN TPM + 1) and relative LM22 ",
    "cell fractions"
  ),
  legend_title = "Spearman rho",
  filename = "05A_cross_cancer_spearman_heatmap.png"
)

manifest <- rbind(
  manifest,
  data.table(
    figure = "05A",
    description = "Cross-cancer continuous Spearman correlation heatmap",
    file = rho_path
  )
)

# ==============================================================================
# Figure 05B: CD43-high versus CD43-low effect-size heatmap
# ==============================================================================

effect_plot_data <- prepare_heatmap_data(
  categorical,
  value_column = "rank_biserial",
  fdr_column = "wilcoxon_FDR"
)

effect_path <- make_heatmap(
  effect_plot_data,
  title = "Immune composition differs between CD43-high and CD43-low tumors",
  subtitle = paste0(
    "Rank-biserial effects comparing the upper and lower cancer-specific ",
    "SPN-expression quartiles"
  ),
  legend_title = "Rank-biserial\neffect",
  filename = "05B_cross_cancer_rank_biserial_heatmap.png"
)

manifest <- rbind(
  manifest,
  data.table(
    figure = "05B",
    description = "Cross-cancer CD43-high versus CD43-low effect-size heatmap",
    file = effect_path
  )
)

# ==============================================================================
# Figure 05C: complete LM22 composition in CD43-low and CD43-high tumors
# ==============================================================================

composition_long <- melt(
  sample_data[CD43_group %in% c("CD43_low", "CD43_high")],
  id.vars = c("sample_id", "cancer", "CD43_group"),
  measure.vars = names(lm22_palette),
  variable.name = "cell_type",
  value.name = "fraction"
)

if (any(!is.finite(composition_long$fraction))) {
  stop("Non-finite LM22 fractions were found in the analysis-ready table.")
}

if (any(composition_long$fraction < 0 | composition_long$fraction > 1)) {
  stop("LM22 fractions outside the interval [0, 1] were detected.")
}

composition_long[, CD43_group := factor(
  CD43_group,
  levels = c("CD43_low", "CD43_high"),
  labels = c("CD43 low", "CD43 high")
)]
composition_long[, cancer := factor(cancer, levels = cancer_order)]
composition_long[, cell_type := factor(
  cell_type,
  levels = rev(names(lm22_palette))
)]

# The arithmetic mean is used because the mean fractions retain the
# compositional sum of one. Independently calculated medians would not.
composition_summary <- composition_long[, .(
  mean_fraction = mean(fraction),
  sd_fraction = sd(fraction),
  median_fraction = median(fraction),
  n_samples = uniqueN(sample_id)
), by = .(cancer, CD43_group, cell_type)]

composition_summary[, group_total := sum(mean_fraction),
                    by = .(cancer, CD43_group)]

# Store join and reshaping keys as plain character columns to avoid factor
# level mismatches when combining them with the statistical results.
composition_summary[, cancer := as.character(cancer)]
composition_summary[, cell_type := as.character(cell_type)]

if (any(abs(composition_summary$group_total - 1) > 0.01)) {
  warning(
    "At least one group-level mean composition differs from 1 by more than ",
    "0.01. Review CIBERSORTx fraction sums."
  )
}

composition_file <- file.path(results_dir, "05_composition_summary.csv")
fwrite(composition_summary, composition_file)

# Put the two group means on the same row so their absolute abundance can be
# compared directly in the butterfly profiles.
composition_wide <- dcast(
  composition_summary,
  cancer + cell_type ~ CD43_group,
  value.var = "mean_fraction"
)
setnames(
  composition_wide,
  c("CD43 low", "CD43 high"),
  c("mean_low", "mean_high")
)
composition_wide[, difference_high_minus_low := mean_high - mean_low]
composition_wide[, difference_percentage_points :=
  100 * difference_high_minus_low]

composition_wide <- merge(
  composition_wide,
  categorical[, .(cancer, cell_type, wilcoxon_FDR)],
  by = c("cancer", "cell_type"),
  all.x = TRUE,
  sort = FALSE
)
composition_wide[, significant := wilcoxon_FDR <= 0.05]

# ==============================================================================
# Per-cancer butterfly composition profiles
# ==============================================================================

per_cancer_dir <- file.path(figure_dir, "per_cancer")
dir.create(per_cancer_dir, recursive = TRUE, showWarnings = FALSE)

for (cancer_name in butterfly_cancers) {
  cancer_data <- copy(
    composition_wide[as.character(cancer) == cancer_name]
  )
  sample_counts <- unique(
    composition_summary[as.character(cancer) == cancer_name,
                        .(CD43_group, n_samples)]
  )
  count_subtitle <- paste(
    paste0(sample_counts$CD43_group, ": n = ", sample_counts$n_samples),
    collapse = "; "
  )

  cancer_ordered_cells <- cancer_data[
    order(-(mean_low + mean_high) / 2)
  ]$cell_type
  cancer_data[, cell_type := factor(
    as.character(cell_type),
    levels = rev(as.character(cancer_ordered_cells))
  )]

  profile_maximum <- max(
    cancer_data$mean_low,
    cancer_data$mean_high,
    na.rm = TRUE
  )
  profile_limit <- profile_maximum * 1.22
  label_offset <- max(0.0025, profile_maximum * 0.022)

  cancer_data[, low_label := fifelse(
    mean_low >= 0.01,
    label_percent(accuracy = 0.1)(mean_low),
    ""
  )]
  cancer_data[, high_label := fifelse(
    mean_high >= 0.01,
    label_percent(accuracy = 0.1)(mean_high),
    ""
  )]
  cancer_data[, significance_label := fifelse(
    significant == TRUE,
    "•",
    ""
  )]
  cancer_data[, significance_x := profile_limit * 0.97]

  cancer_plot <- ggplot(
    cancer_data,
    aes(y = cell_type)
  ) +
    geom_vline(
      xintercept = 0,
      colour = "grey35",
      linewidth = 0.45
    ) +
    geom_col(
      aes(
        x = -mean_low,
        fill = "CD43 low",
        colour = "CD43 low"
      ),
      width = 0.62,
      linewidth = 0.40
    ) +
    geom_col(
      aes(
        x = mean_high,
        fill = "CD43 high",
        colour = "CD43 high"
      ),
      width = 0.62,
      linewidth = 0.40
    ) +
    geom_text(
      aes(
        x = -mean_low - label_offset,
        label = low_label
      ),
      hjust = 1,
      size = 2.6,
      colour = cd43_low_text
    ) +
    geom_text(
      aes(
        x = mean_high + label_offset,
        label = high_label
      ),
      hjust = 0,
      size = 2.6,
      colour = cd43_high_text
    ) +
    geom_text(
      aes(x = significance_x, label = significance_label),
      size = 3.0,
      fontface = "bold",
      colour = significance_colour
    ) +
    scale_fill_manual(
      values = c(
        "CD43 low" = scales::alpha(cd43_low_colour, 0.40),
        "CD43 high" = scales::alpha(cd43_high_colour, 0.40)
      ),
      name = NULL
    ) +
    scale_colour_manual(
      values = c(
        "CD43 low" = cd43_low_border,
        "CD43 high" = cd43_high_border
      ),
      name = NULL
    ) +
    scale_x_continuous(
      limits = c(-profile_limit, profile_limit),
      labels = function(x) label_percent(accuracy = 1)(abs(x)),
      breaks = pretty_breaks(n = 7),
      expand = expansion(mult = c(0.01, 0.01))
    ) +
    labs(
      title = paste0(cancer_name, ": immune composition by CD43 group"),
      subtitle = paste0(
        "CD43 low extends left; CD43 high extends right | ",
        count_subtitle
      ),
      x = "Mean relative LM22 fraction (%)",
      y = NULL,
      caption = paste0(
        "Cell types are ordered by average abundance across both groups. ",
        "Values below 1% are not labeled; • indicates BH-FDR <= 0.05."
      )
    ) +
    project_theme(base_size = 11) +
    theme(
      axis.text.y = element_text(size = 8.5),
      legend.position = "top",
      legend.justification = "left",
      legend.text = element_text(size = 8.5),
      panel.grid.major.y = element_line(
        colour = row_guide_colour,
        linewidth = 0.35
      ),
      panel.grid.major.x = element_blank(),
      legend.key.width = unit(0.7, "cm")
    )

  cancer_filename <- paste0(
    "05C_", cancer_name, "_CD43_butterfly_profile.png"
  )
  cancer_path <- file.path(per_cancer_dir, cancer_filename)

  ggsave(
    filename = cancer_path,
    plot = cancer_plot,
    width = 8.5,
    height = 8.5,
    dpi = 600,
    bg = "white"
  )
  message("Saved: ", cancer_path)

  manifest <- rbind(
    manifest,
    data.table(
      figure = paste0("05C-", cancer_name),
      description = paste0(
        cancer_name,
        " butterfly LM22 composition profile for CD43-low and CD43-high tumors"
      ),
      file = cancer_path
    )
  )
}

# ==============================================================================
# Save manifest and report completion
# ==============================================================================

manifest_file <- file.path(results_dir, "05_figure_manifest.csv")
fwrite(manifest, manifest_file)

message("All CD43 immune-association figures were generated successfully.")
print(manifest)
writeLines(
  capture.output(sessionInfo()),
  file.path(results_dir, "05_sessionInfo.txt")
)
